cert_file: .ssh/id_rsa/dev_pubkey.pem
database_path: db/data/tagsdb.sqlite
key_file: .ssh/id_rsa/dev_secret.pem
rfid_field_name: Door Key
training_field_name: Safety Training
wild_apricot_account_id: 12345
