version: '3.8'

services:
  dingus:
    build:
      context: ./src/dingus
      dockerfile: DOCKERFILE
    ports:
      - "443:443"
    volumes:
      - type: bind
        source: ./certs/dev_pubkey.pem
        target: /home/dingus/certs/dev_pubkey.pem
        read_only: true
      - type: bind
        source: ./certs/dev_secret.pem
        target: /home/dingus/certs/dev_secret.pem
        read_only: true
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - db
      - default
    user: dingus

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/dingus/pkg/db/schema/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./src/dingus/pkg/db/schema/tagsdb.sql:/docker-entrypoint-initdb.d/tagsdb.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - db
    restart: on-failure:3

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  my_db_volume:

networks:
  db:
  default:
